- name: add fish to shells
  shell: sudo sh -c 'echo /opt/homebrew/bin/fish >> /etc/shells'
  become: true
  tags: dotfiles
- name: clone Dotfiles
  shell: yadm clone https://github.com/Askath/Dotfiles.git
  tags: dotfiles

- name: install tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /Users/taradruffel/.tmux/plugins/tpm
  tags: dotfiles
