- hosts: localhost
  become: false
  ignore_errors: true
  tasks:
    - include_tasks: tools/taps.yml
      tags: taps
    - include_tasks: tools/tools.yml
      tags: tools
    - include_tasks: dotfiles.yml
      tags: dotfiles
    - include_tasks: fish_config.yml
      tags: fish_config

